### ISSUE TITLE
Correct comments

### ISSUE THREAD

**Issue by danij** [CruceGameDevel/CruceGame#94]
A lot of comments use very poor English and are hard to understand

**Comment by Paul92** [comment]
fixed in 1b10d72

**Comment by danij** [comment]
Still not ready. Will correct the remaining ones this weekend
